apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-repl-01
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc-sample
  volumeMode: Filesystem
  volumeName: pvc-static-horcm-01
